---
# https://github.com/remote-android/redroid-doc/blob/master/deploy/fedora.md

- name: grubby --update-kernel
  ansible.builtin.shell: grubby --update-kernel ALL --args selinux=0
  args:
    creates: "{{ deploy_log }}"
  become: true

- name: grub2-mkconfig
  ansible.builtin.shell: grub2-mkconfig > /boot/grub2/grub.cfg
  args:
    creates: "{{ deploy_log }}"
  become: true
  notify:
  - Idempotent directory
  - Reboot

- name: modprobe nfnetlink
  community.general.modprobe:
    name: nfnetlink
    state: present
    persistent: present
  become: true

- name: Docker image
  include_tasks: .fn/Docker pull.yml

- name: Force Reboot
  meta: flush_handlers