- name: Create bin directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/bin"
    state: directory
    mode: '0755'

- name: Template a redroid.sh to bin
  ansible.builtin.template:
    src: "{{ default_template }}"
    dest: "{{ ansible_env.HOME }}/bin/redroid.sh"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0744'